namespace UnovaRPGlib
{
    public enum Pokemon
    {
        None,
        #region gen1
        Bulbasaur,
        Ivysaur,
        Venusaur,
        Charmander,
        Charmeleon,
        Charizard,
        Squirtle,
        Wartortle,
        Blastoise,
        Caterpie,
        Metapod,
        Butterfree,
        Weedle,
        Kakuna,
        Beedrill,
        Pidgey,
        Pidgeotto,
        Pidgeot,
        Rattata,
        Raticate,
        Spearow,
        Fearow,
        Ekans,
        Arbok,
        Pikachu,
        Raichu,
        Sandshrew,
        Sandslash,
        NidoranF,
        Nidorina,
        Nidoqueen,
        NidoranM,
        Nidorino,
        Nidoking,
        Clefairy,
        Clefable,
        Vulpix,
        Ninetales,
        Jigglypuff,
        Wigglytuff,
        Zubat,
        Golbat,
        Oddish,
        Gloom,
        Vileplume,
        Paras,
        Parasect,
        Venonat,
        Venomoth,
        Diglett,
        Dugtrio,
        Meowth,
        Persian,
        Psyduck,
        Golduck,
        Mankey,
        Primeape,
        Growlithe,
        Arcanine,
        Poliwag,
        Poliwhirl,
        Poliwrath,
        Abra,
        Kadabra,
        Alakazam,
        Machop,
        Machoke,
        Machamp,
        Bellsprout,
        Weepinbell,
        Victreebel,
        Tentacool,
        Tentacruel,
        Geodude,
        Graveler,
        Golem,
        Ponyta,
        Rapidash,
        Slowpoke,
        Slowbro,
        Magnemite,
        Magneton,
        Farfetchd,
        Doduo,
        Dodrio,
        Seel,
        Dewgong,
        Grimer,
        Muk,
        Shellder,
        Cloyster,
        Gastly,
        Haunter,
        Gengar,
        Onix,
        Drowzee,
        Hypno,
        Krabby,
        Kingler,
        Voltorb,
        Electrode,
        Exeggcute,
        Exeggutor,
        Cubone,
        Marowak,
        Hitmonlee,
        Hitmonchan,
        Lickitung,
        Koffing,
        Weezing,
        Rhyhorn,
        Rhydon,
        Chansey,
        Tangela,
        Kangaskhan,
        Horsea,
        Seadra,
        Goldeen,
        Seaking,
        Staryu,
        Starmie,
        MrMime,
        Scyther,
        Jynx,
        Electabuzz,
        Magmar,
        Pinsir,
        Tauros,
        Magikarp,
        Gyarados,
        Lapras,
        Ditto,
        Eevee,
        Vaporeon,
        Jolteon,
        Flareon,
        Porygon,
        Omanyte,
        Omastar,
        Kabuto,
        Kabutops,
        Aerodactyl,
        Snorlax,
        Articuno,
        Zapdos,
        Moltres,
        Dratini,
        Dragonair,
        Dragonite,
        Mewtwo,
        Mew,
        #endregion
        #region gen2
        Chikorita,
        Bayleef,
        Meganium,
        Cyndaquil,
        Quilava,
        Typhlosion,
        Totodile,
        Croconaw,
        Feraligatr,
        Sentret,
        Furret,
        Hoothoot,
        Noctowl,
        Ledyba,
        Ledian,
        Spinarak,
        Ariados,
        Crobat,
        Chinchou,
        Lanturn,
        Pichu,
        Cleffa,
        Igglybuff,
        Togepi,
        Togetic,
        Natu,
        Xatu,
        Mareep,
        Flaaffy,
        Ampharos,
        Bellossom,
        Marill,
        Azumarill,
        Sudowoodo,
        Politoed,
        Hoppip,
        Skiploom,
        Jumpluff,
        Aipom,
        Sunkern,
        Sunflora,
        Yanma,
        Wooper,
        Quagsire,
        Espeon,
        Umbreon,
        Murkrow,
        Slowking,
        Misdreavus,
        Unown,
        Wobbuffet,
        Girafarig,
        Pineco,
        Forretress,
        Dunsparce,
        Gligar,
        Steelix,
        Snubbull,
        Granbull,
        Qwilfish,
        Scizor,
        Shuckle,
        Heracross,
        Sneasel,
        Teddiursa,
        Ursaring,
        Slugma,
        Magcargo,
        Swinub,
        Piloswine,
        Corsola,
        Remoraid,
        Octillery,
        Delibird,
        Mantine,
        Skarmory,
        Houndour,
        Houndoom,
        Kingdra,
        Phanpy,
        Donphan,
        Porygon2,
        Stantler,
        Smeargle,
        Tyrogue,
        Hitmontop,
        Smoochum,
        Elekid,
        Magby,
        Miltank,
        Blissey,
        Raikou,
        Entei,
        Suicune,
        Larvitar,
        Pupitar,
        Tyranitar,
        Lugia,
        HoOh,
        Celebi,
        #endregion
        #region gen3
        Treecko,
        Grovyle,
        Sceptile,
        Torchic,
        Combusken,
        Blaziken,
        Mudkip,
        Marshtomp,
        Swampert,
        Poochyena,
        Mightyena,
        Zigzagoon,
        Linoone,
        Wurmple,
        Silcoon,
        Beautifly,
        Cascoon,
        Dustox,
        Lotad,
        Lombre,
        Ludicolo,
        Seedot,
        Nuzleaf,
        Shiftry,
        Taillow,
        Swellow,
        Wingull,
        Pelipper,
        Ralts,
        Kirlia,
        Gardevoir,
        Surskit,
        Masquerain,
        Shroomish,
        Breloom,
        Slakoth,
        Vigoroth,
        Slaking,
        Nincada,
        Ninjask,
        Shedinja,
        Whismur,
        Loudred,
        Exploud,
        Makuhita,
        Hariyama,
        Azurill,
        Nosepass,
        Skitty,
        Delcatty,
        Sableye,
        Mawile,
        Aron,
        Lairon,
        Aggron,
        Meditite,
        Medicham,
        Electrike,
        Manectric,
        Plusle,
        Minun,
        Volbeat,
        Illumise,
        Roselia,
        Gulpin,
        Swalot,
        Carvanha,
        Sharpedo,
        Wailmer,
        Wailord,
        Numel,
        Camerupt,
        Torkoal,
        Spoink,
        Grumpig,
        Spinda,
        Trapinch,
        Vibrava,
        Flygon,
        Cacnea,
        Cacturne,
        Swablu,
        Altaria,
        Zangoose,
        Seviper,
        Lunatone,
        Solrock,
        Barboach,
        Whiscash,
        Corphish,
        Crawdaunt,
        Baltoy,
        Claydol,
        Lileep,
        Cradily,
        Anorith,
        Armaldo,
        Feebas,
        Milotic,
        Castform,
        Kecleon,
        Shuppet,
        Banette,
        Duskull,
        Dusclops,
        Tropius,
        Chimecho,
        Absol,
        Wynaut,
        Snorunt,
        Glalie,
        Spheal,
        Sealeo,
        Walrein,
        Clamperl,
        Huntail,
        Gorebyss,
        Relicanth,
        Luvdisc,
        Bagon,
        Shelgon,
        Salamence,
        Beldum,
        Metang,
        Metagross,
        Regirock,
        Regice,
        Registeel,
        Latias,
        Latios,
        Kyogre,
        Groudon,
        Rayquaza,
        Jirachi,
        Deoxys,
        #endregion
        #region gen4
        Turtwig,
        Grotle,
        Torterra,
        Chimchar,
        Monferno,
        Infernape,
        Piplup,
        Prinplup,
        Empoleon,
        Starly,
        Staravia,
        Staraptor,
        Bidoof,
        Bibarel,
        Kricketot,
        Kricketune,
        Shinx,
        Luxio,
        Luxray,
        Budew,
        Roserade,
        Cranidos,
        Rampardos,
        Shieldon,
        Bastiodon,
        Burmy,
        Wormadam,
        Mothim,
        Combee,
        Vespiquen,
        Pachirisu,
        Buizel,
        Floatzel,
        Cherubi,
        Cherrim,
        Shellos,
        Gastrodon,
        Ambipom,
        Drifloon,
        Drifblim,
        Buneary,
        Lopunny,
        Mismagius,
        Honchkrow,
        Glameow,
        Purugly,
        Chingling,
        Stunky,
        Skuntank,
        Bronzor,
        Bronzong,
        Bonsly,
        MimeJr,
        Happiny,
        Chatot,
        Spiritomb,
        Gible,
        Gabite,
        Garchomp,
        Munchlax,
        Riolu,
        Lucario,
        Hippopotas,
        Hippowdon,
        Skorupi,
        Drapion,
        Croagunk,
        Toxicroak,
        Carnivine,
        Finneon,
        Lumineon,
        Mantyke,
        Snover,
        Abomasnow,
        Weavile,
        Magnezone,
        Lickilicky,
        Rhyperior,
        Tangrowth,
        Electivire,
        Magmortar,
        Togekiss,
        Yanmega,
        Leafeon,
        Glaceon,
        Gliscor,
        Mamoswine,
        PorygonZ,
        Gallade,
        Probopass,
        Dusknoir,
        Froslass,
        Rotom,
        Uxie,
        Mesprit,
        Azelf,
        Dialga,
        Palkia,
        Heatran,
        Regigigas,
        Giratina,
        Cresselia,
        Phione,
        Manaphy,
        Darkrai,
        Shaymin,
        Arceus,
        #endregion
        #region gen5
        Victini,
        Snivy,
        Servine,
        Serperior,
        Tepig,
        Pignite,
        Emboar,
        Oshawott,
        Dewott,
        Samurott,
        Patrat,
        Watchog,
        Lillipup,
        Herdier,
        Stoutland,
        Purrloin,
        Liepard,
        Pansage,
        Simisage,
        Pansear,
        Simisear,
        Panpour,
        Simipour,
        Munna,
        Musharna,
        Pidove,
        Tranquill,
        Unfezant,
        Blitzle,
        Zebstrika,
        Roggenrola,
        Boldore,
        Gigalith,
        Woobat,
        Swoobat,
        Drilbur,
        Excadrill,
        Audino,
        Timburr,
        Gurdurr,
        Conkeldurr,
        Tympole,
        Palpitoad,
        Seismitoad,
        Throh,
        Sawk,
        Sewaddle,
        Swadloon,
        Leavanny,
        Venipede,
        Whirlipede,
        Scolipede,
        Cottonee,
        Whimsicott,
        Petilil,
        Lilligant,
        Basculin,
        Sandile,
        Krokorok,
        Krookodile,
        Darumaka,
        Darmanitan,
        Maractus,
        Dwebble,
        Crustle,
        Scraggy,
        Scrafty,
        Sigilyph,
        Yamask,
        Cofagrigus,
        Tirtouga,
        Carracosta,
        Archen,
        Archeops,
        Trubbish,
        Garbodor,
        Zorua,
        Zoroark,
        Minccino,
        Cinccino,
        Gothita,
        Gothorita,
        Gothitelle,
        Solosis,
        Duosion,
        Reuniclus,
        Ducklett,
        Swanna,
        Vanillite,
        Vanillish,
        Vanilluxe,
        Deerling,
        Sawsbuck,
        Emolga,
        Karrablast,
        Escavalier,
        Foongus,
        Amoonguss,
        Frillish,
        Jellicent,
        Alomomola,
        Joltik,
        Galvantula,
        Ferroseed,
        Ferrothorn,
        Klink,
        Klang,
        Klinklang,
        Tynamo,
        Eelektrik,
        Eelektross,
        Elgyem,
        Beheeyem,
        Litwick,
        Lampent,
        Chandelure,
        Axew,
        Fraxure,
        Haxorus,
        Cubchoo,
        Beartic,
        Cryogonal,
        Shelmet,
        Accelgor,
        Stunfisk,
        Mienfoo,
        Mienshao,
        Druddigon,
        Golett,
        Golurk,
        Pawniard,
        Bisharp,
        Bouffalant,
        Rufflet,
        Braviary,
        Vullaby,
        Mandibuzz,
        Heatmor,
        Durant,
        Deino,
        Zweilous,
        Hydreigon,
        Larvesta,
        Volcarona,
        Cobalion,
        Terrakion,
        Virizion,
        Tornadus,
        Thundurus,
        Reshiram,
        Zekrom,
        Landorus,
        Kyurem,
        Keldeo,
        Meloetta,
        Genesect,
        #endregion
        #region gen6
        Chespin,
        Quilladin,
        Chesnaught,
        Fennekin,
        Braixen,
        Delphox,
        Froakie,
        Frogadier,
        Greninja,
        Bunnelby,
        Diggersby,
        Fletchling,
        Fletchinder,
        Talonflame,
        Scatterbug,
        Spewpa,
        Vivillon,
        Litleo,
        Pyroar,
        Flabébé,
        Floette,
        Florges,
        Skiddo,
        Gogoat,
        Pancham,
        Pangoro,
        Furfrou,
        Espurr,
        Meowstic,
        Honedge,
        Doublade,
        Aegislash,
        Spritzee,
        Aromatisse,
        Swirlix,
        Slurpuff,
        Inkay,
        Malamar,
        Binacle,
        Barbaracle,
        Skrelp,
        Dragalge,
        Clauncher,
        Clawitzer,
        Helioptile,
        Heliolisk,
        Tyrunt,
        Tyrantrum,
        Amaura,
        Aurorus,
        Sylveon,
        Hawlucha,
        Dedenne,
        Carbink,
        Goomy,
        Sliggoo,
        Goodra,
        Klefki,
        Phantump,
        Trevenant,
        Pumpkaboo,
        Gourgeist,
        Bergmite,
        Avalugg,
        Noibat,
        Noivern,
        Xerneas,
        Yveltal,
        Zygarde,
        Diancie,
        Hoopa,
        Volcanion,
        #endregion
        #region gen7
        Rowlet,
        Dartrix,
        Decidueye,
        Litten,
        Torracat,
        Incineroar,
        Popplio,
        Brionne,
        Primarina,
        Pikipek,
        Trumbeak,
        Toucannon,
        Yungoos,
        Gumshoos,
        Grubbin,
        Charjabug,
        Vikavolt,
        Crabrawler,
        Crabominable,
        Oricorio,
        Cutiefly,
        Ribombee,
        Rockruff,
        Lycanroc,
        Wishiwashi,
        Mareanie,
        Toxapex,
        Mudbray,
        Mudsdale,
        Dewpider,
        Araquanid,
        Fomantis,
        Lurantis,
        Morelull,
        Shiinotic,
        Salandit,
        Salazzle,
        Stufful,
        Bewear,
        Bounsweet,
        Steenee,
        Tsareena,
        Comfey,
        Oranguru,
        Passimian,
        Wimpod,
        Golisopod,
        Sandygast,
        Palossand,
        Pyukumuku,
        TypeNull,
        Silvally,
        Minior,
        Komala,
        Turtonator,
        Togedemaru,
        Mimikyu,
        Bruxish,
        Drampa,
        Dhelmise,
        JangmoO,
        HakamoO,
        KommoO,
        TapuKoko,
        TapuLele,
        TapuBulu,
        TapuFini,
        Cosmog,
        Cosmoem,
        Solgaleo,
        Lunala,
        Nihilego,
        Buzzwole,
        Pheromosa,
        Xurkitree,
        Celesteela,
        Kartana,
        Guzzlord,
        Necrozma,
        Magearna,
        Marshadow,
        #endregion
        #region gen7+
        //Poipole,
        //Naganadel,
        //Stakataka,
        //Blacephalon,
        //Zeraora,
        #endregion
    }

    public enum Move
    {
        Absorb = 001,
        Acid = 002,
        AcidArmor = 003,

        AerialAce = 005,

        Agility = 007,
        AirCutter = 008,
        AirSlash = 009,
        Amnesia = 010,
        AncientPower = 011,
        AquaJet = 012,
        AquaRing = 013,
        AquaTail = 014,
        ArmThrust = 015,
        Aromatherapy = 016,
        Assist = 017,
        Assurance = 018,
        Astonish = 019,

        Attract = 021,
        AuraSphere = 022,
        AuroraBeam = 023,
        Avalanche = 024,
        Barrage = 025,
        Barrier = 026,
        BatonPass = 027,

        BellyDrum = 029,
        Bide = 030,
        Bind = 031,
        Bite = 032,

        BlazeKick = 034,
        Blizzard = 035,

        BodySlam = 037,
        BoneClub = 038,
        BoneRush = 039,
        Bonemerang = 040,
        Bounce = 041,
        BraveBird = 042,
        BrickBreak = 043,
        Brine = 044,
        Bubble = 045,
        Bubblebeam = 046,
        BugBite = 047,
        BugBuzz = 048,
        BulkUp = 049,
        BulletPunch = 050,

        CalmMind = 052,
        Camouflage = 053,
        Captivate = 054,
        Charge = 055,
        ChargeBeam = 056,
        Charm = 057,

        Clamp = 059,
        CloseCombat = 060,
        CometPunch = 061,
        ConfuseRay = 062,
        Confusion = 063,
        Constrict = 064,
        Conversion = 065,
        Conversion2 = 066,
        Copycat = 067,
        CosmicPower = 068,
        CottonSpore = 069,
        Counter = 070,
        Covet = 071,

        CrossChop = 073,
        CrossPoison = 074,
        Crunch = 075,
        CrushClaw = 076,

        Curse = 078,
        Cut = 079,
        DarkPulse = 080,

        DefenseCurl = 082,

        Defog = 084,
        DestinyBond = 085,
        Detect = 086,
        Dig = 087,
        Disable = 088,
        Discharge = 089,

        DizzyPunch = 091,

        DoubleHit = 093,
        DoubleKick = 094,
        DoubleTeam = 095,
        Doubleedge = 096,
        Doubleslap = 097,

        DragonClaw = 099,
        DragonDance = 100,
        DragonPulse = 101,
        DragonRage = 102,
        DragonRush = 103,
        Dragonbreath = 104,

        DreamEater = 106,


        EarthPower = 109,
        Earthquake = 110,
        EggBomb = 111,
        Embargo = 112,
        Ember = 113,
        Encore = 114,
        Endeavor = 115,
        Endure = 116,


        Explosion = 119,
        Extrasensory = 120,
        Extremespeed = 121,
        Facade = 122,
        FaintAttack = 123,
        FakeOut = 124,
        FakeTears = 125,
        FalseSwipe = 126,
        Featherdance = 127,
        Feint = 128,
        FireBlast = 129,
        FireFang = 130,
        FirePunch = 131,
        FireSpin = 132,

        Flail = 134,
        FlameWheel = 135,
        Flamethrower = 136,
        FlareBlitz = 137,
        Flash = 138,
        FlashCannon = 139,
        Flatter = 140,
        Fling = 141,
        Fly = 142,

        FocusEnergy = 144,
        FocusPunch = 145,
        FollowMe = 146,
        ForcePalm = 147,
        Foresight = 148,


        FuryAttack = 151,
        FuryCutter = 152,
        FurySwipes = 153,
        FutureSight = 154,
        GastroAcid = 155,
        GigaDrain = 156,
        GigaImpact = 157,
        Glare = 158,

        Grasswhistle = 160,
        Gravity = 161,
        Growl = 162,
        Growth = 163,

        GuardSwap = 165,
        Guillotine = 166,
        GunkShot = 167,
        Gust = 168,
        GyroBall = 169,
        Hail = 170,
        HammerArm = 171,
        Harden = 172,
        Haze = 173,
        HeadSmash = 174,
        Headbutt = 175,
        HealBell = 176,
        HealBlock = 177,

        HealingWish = 179,

        HeatWave = 181,
        HelpingHand = 182,
        HiJumpKick = 183,
        HiddenPower = 184,
        HornAttack = 185,
        HornDrill = 186,
        Howl = 187,

        HydroPump = 189,
        HyperBeam = 190,
        HyperFang = 191,
        HyperVoice = 192,
        Hypnosis = 193,
        IceBall = 194,
        IceBeam = 195,
        IceFang = 196,
        IcePunch = 197,
        IceShard = 198,
        IcicleSpear = 199,
        IcyWind = 200,
        Imprison = 201,
        Ingrain = 202,
        IronDefense = 203,
        IronHead = 204,
        IronTail = 205,
        Judgment = 206,
        JumpKick = 207,
        KarateChop = 208,

        KnockOff = 210,
        LastResort = 211,
        LavaPlume = 212,
        LeafBlade = 213,
        LeafStorm = 214,
        LeechLife = 215,
        LeechSeed = 216,
        Leer = 217,
        Lick = 218,
        LightScreen = 219,
        Lockon = 220,
        LovelyKiss = 221,
        LowKick = 222,
        LuckyChant = 223,

        LusterPurge = 225,
        MachPunch = 226,
        MagicCoat = 227,
        MagicalLeaf = 228,

        MagnetBomb = 230,
        MagnetRise = 231,
        Magnitude = 232,
        MeFirst = 233,
        MeanLook = 234,
        Meditate = 235,
        MegaDrain = 236,
        MegaKick = 237,
        MegaPunch = 238,
        Megahorn = 239,
        Memento = 240,
        MetalBurst = 241,
        MetalClaw = 242,
        MetalSound = 243,
        MeteorMash = 244,
        Metronome = 245,

        Mimic = 247,
        MindReader = 248,
        Minimize = 249,
        MiracleEye = 250,
        MirrorCoat = 251,

        MirrorShot = 253,

        MistBall = 255,
        Moonlight = 256,
        MorningSun = 257,
        MudBomb = 258,
        MudShot = 259,
        MudSport = 260,
        Mudslap = 261,
        MuddyWater = 262,
        NastyPlot = 263,
        NaturalGift = 264,
        NaturePower = 265,

        NightShade = 267,
        NightSlash = 268,
        Nightmare = 269,

        OdorSleuth = 271,
        OminousWind = 272,
        Outrage = 273,



        Payback = 277,
        Peck = 278,
        PerishSong = 279,
        PetalDance = 280,
        PinMissile = 281,
        Pluck = 282,

        PoisonGas = 284,
        PoisonJab = 285,
        PoisonSting = 286,
        PoisonTail = 287,
        Poisonpowder = 288,
        Pound = 289,
        PowderSnow = 290,
        PowerGem = 291,
        PowerSwap = 292,
        PowerTrick = 293,
        PowerWhip = 294,
        Present = 295,
        Protect = 296,
        Psybeam = 297,
        PsychUp = 298,
        Psychic = 299,

        PsychoCut = 301,

        Psywave = 303,
        Punishment = 304,
        Pursuit = 305,
        QuickAttack = 306,
        Rage = 307,
        RainDance = 308,
        RapidSpin = 309,
        RazorLeaf = 310,
        RazorWind = 311,
        Recover = 312,
        Recycle = 313,
        Reflect = 314,
        Refresh = 315,
        Rest = 316,

        Revenge = 318,
        Reversal = 319,
        Roar = 320,
        RoarOfTime = 321,
        RockBlast = 322,
        RockClimb = 323,
        RockPolish = 324,
        RockSlide = 325,
        RockSmash = 326,
        RockThrow = 327,
        RockTomb = 328,

        RolePlay = 330,
        RollingKick = 331,
        Rollout = 332,
        Roost = 333,

        Safeguard = 335,
        SandTomb = 336,
        Sandattack = 337,
        Sandstorm = 338,
        ScaryFace = 339,
        Scratch = 340,
        Screech = 341,
        SecretPower = 342,
        SeedBomb = 343,

        SeismicToss = 345,
        Selfdestruct = 346,
        ShadowBall = 347,
        ShadowClaw = 348,
        ShadowForce = 349,
        ShadowPunch = 350,
        ShadowSneak = 351,
        Sharpen = 352,
        SheerCold = 353,
        ShockWave = 354,
        SignalBeam = 355,
        SilverWind = 356,
        Sing = 357,

        SkillSwap = 359,
        SkullBash = 360,
        SkyAttack = 361,
        SkyUppercut = 362,
        SlackOff = 363,
        Slam = 364,
        Slash = 365,
        SleepPowder = 366,
        SleepTalk = 367,

        SludgeBomb = 369,

        Smog = 371,
        Smokescreen = 372,
        Snatch = 373,
        Snore = 374,
        Softboiled = 375,

        Sonicboom = 377,
        SpacialRend = 378,
        Spark = 379,
        SpiderWeb = 380,
        SpikeCannon = 381,
        Spikes = 382,
        SpitUp = 383,
        Spite = 384,
        Splash = 385,

        StealthRock = 387,

        Stockpile = 389,
        Stomp = 390,
        StoneEdge = 391,

        StringShot = 393,

        StunSpore = 395,

        Substitute = 397,
        SuckerPunch = 398,
        SunnyDay = 399,
        SuperFang = 400,
        Superpower = 401,
        Supersonic = 402,

        Swagger = 404,
        Swallow = 405,
        SweetKiss = 406,
        SweetScent = 407,
        Swift = 408,
        Switcheroo = 409,
        SwordsDance = 410,
        Synthesis = 411,
        Tackle = 412,
        TailGlow = 413,
        TailWhip = 414,
        Tailwind = 415,
        TakeDown = 416,
        Taunt = 417,
        TeeterDance = 418,


        Thrash = 421,
        Thunder = 422,
        ThunderFang = 423,
        ThunderWave = 424,
        Thunderbolt = 425,
        Thunderpunch = 426,
        Thundershock = 427,
        Tickle = 428,
        Torment = 429,
        Toxic = 430,
        ToxicSpikes = 431,
        Transform = 432,
        TriAttack = 433,
        Trick = 434,
        TrickRoom = 435,
        TripleKick = 436,

        Twineedle = 438,
        Twister = 439,
        Uturn = 440,
        Uproar = 441,
        VacuumWave = 442,
        Vicegrip = 443,
        VineWhip = 444,
        VitalThrow = 445,

        WakeupSlap = 447,
        WaterGun = 448,
        WaterPulse = 449,
        WaterSport = 450,
        WaterSpout = 451,


        Whirlpool = 454,
        Whirlwind = 455,
        Willowisp = 456,
        WingAttack = 457,
        Wish = 458,
        Withdraw = 459,
        WoodHammer = 460,
        WorrySeed = 461,
        Wrap = 462,
        WringOut = 463,
        Xscissor = 464,
        Yawn = 465,

        ZenHeadbutt = 467,
        Teleport = 468,
        Thief = 469,
        Mist = 470,
        Sludge = 471,




        AcidBomb = 476,


        AncientSong = 479,


        BarkOut = 482,
        BlazeJudgement = 483,
        BlueFlame = 484,

        BoilingWater = 486,
        BugOpposition = 487,

        ButterflyDance = 489,


        ClearSmog = 492,

        ColdFlare = 494,



        DoubleChop = 498,
        DragonTail = 499,
        DrillLiner = 500,
        EchoVoice = 501,




        FireDance = 506,


        FreezeBolt = 509,

        Gale = 511,



        GrassMixer = 515,
        GrassOath = 516,
        GuardShare = 517,


        HeartStamp = 520,
        HeatStamp = 521,
        HeavyBomber = 522,



        KnockDown = 526,




        MagicRoom = 531,
        MakeFriends = 532,





        Postpone = 538,

        PowerShare = 540,
        PsychoBreak = 541,
        PsychoShock = 542,

        SacredSword = 544,
        ShellBlade = 545,





        Submersion = 551,

        SwordOfMystery = 553,

        TechnoBuster = 555,



        Vengeance = 559,



        WideGuard = 563,





        BabyDollEyes = 569,
        Belch = 570,


        CraftyShield = 573,

        DisarmingVoice = 575,
        DrainingKiss = 576,
        EerieImpulse = 577,
        ElectricTerrain = 578,


        FairyWind = 581,




        FreezeDry = 586,
        Geomancy = 587,
        GrassyTerrain = 588,





        MatBlock = 594,
        MistyTerrain = 595,
        Moonblast = 596,
        MysticalFire = 597,
        NobleRoar = 598,

        OblivionWing = 600,

        PartingShot = 602,

        PhantomForce = 604,
        PlayNice = 605,
        PlayRough = 606,
        Powder = 607,
        PowerUpPunch = 608,
        Rototiller = 609,


        TopsyTurvy = 612,

        VenomDrench = 614,
        WaterShuriken = 615,
        FlameCharge = 616,
        Psyshock = 617,
        Round = 618,
        SmackDown = 619,
        FeintAttack = 620,
        DoubleSlap = 621,
        Bulldoze = 622,
        Acrobatics = 623,
        WorkUp = 624,
        EchoedVoice = 625,
        HornLeech = 626,
        CircleThrow = 627,
        Entrainment = 628,
        Autotomize = 629,

        HealPulse = 631,

        FoulPlay = 633,
        ShellSmash = 634,
        HoneClaws = 635,
        ViceGrip = 636,

        AfterYou = 638,
        AllySwitch = 639,
        Bestow = 640,


        ChipAway = 643,
        DiamondStorm = 644,
        DragonAscent = 645,
        DragonBreath = 646,
        DualChop = 647,
        Electroweb = 648,

        FinalGambit = 650,

        FlameBurst = 652,




        GearGrind = 657,
        Glaciate = 658,

        GuardSplit = 660,


        HeatCrash = 663,

        Hex = 665,


        Hurricane = 668,



        IcicleCrash = 672,
        Inferno = 673,
        LeafTornado = 674,

        LowSweep = 676,

        OriginPulse = 678,
        PowerSplit = 679,
        PrecipiceBlades = 680,
        Psystrike = 681,
        Quash = 682,
        QuickGuard = 683,
        QuiverDance = 684,
        RagePowder = 685,
        RazorShell = 686,
        ReflectType = 687,

        Scald = 689,
        SearingShot = 690,

        ShiftGear = 692,

        Snarl = 694,
        Soak = 695,

        Steamroller = 697,
        StoredPower = 698,

        StruggleBug = 700
    }
}
